Repository Lets-JUPJUP/JUPJUP-Front, pull requests merged in 2023-11, with the labels that each got.

#1 # 20231104 wowalswjd (김민정) 플로깅 리스트 페이지, 광고배너, 플로팅 버튼 퍼블리싱
  src/App.js
  src/assets/PloggingList/ic_reset.png
  src/assets/common/fab_trash.png
  src/assets/common/fab_write.png
  src/assets/common/ic_info.png
  src/assets/common/ic_star_clicked.png
  src/assets/common/ic_star_clicked_main.png
  src/assets/common/ic_star_default.png
  src/assets/common/ic_star_default_main.png
  src/assets/common/ic_tag.png
  src/assets/common/ic_tag_main.png
  src/components/PloggingList/FilteringBox.js
  src/components/PloggingList/PloggingListSection.js
  src/components/common/AdBanner.js
  src/components/common/FloatingButton.js
  src/components/common/PloggingPostBox.js
  src/components/common/Tag.js
  src/pages/PloggingListPage.js
Labels: 💄 publishing

#2 # 20231104 songing01 (송지민) 로그인 화면, 로그인 회원정보 화면, 모집글 작성화면, 유저 신고 / 제보 화면 퍼블리싱
  package-lock.json
  package.json
  src/App.js
  src/assets/common/add.png
  src/assets/common/alarm.png
  src/assets/common/logo.png
  src/assets/common/user.png
  src/assets/create/add.png
  src/assets/login/background.png
  src/assets/login/background2.png
  src/assets/login/edit.png
  src/assets/login/kakao.png
  src/assets/login/logo.png
  src/assets/login/tag.png
  src/components/common/AddPhoto.js
  src/components/common/Header.js
  src/components/create/Form.js
  src/components/create/RangeSlider.js
  src/components/create/marks.js
  src/pages/Login/LoginPage.js
  src/pages/Login/LoginSettingsPage.js
  src/pages/Plogging/CreatePlogPage.js
  src/pages/User/UserReportPage.js
Labels: 💄 publishing

#3 # 20231106 songing01 (송지민) 주최자프로필 페이지, 메인 페이지, 리뷰하기 페이지, 알림모음 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.js
  src/assets/main/mountain.png
  src/assets/user/alarm/alarm_0.png
  src/assets/user/alarm/alarm_1.png
  src/assets/user/alarm/alarm_2.png
  src/assets/user/badges/badge_0.png
  src/assets/user/badges/badge_1.png
  src/assets/user/badges/badge_10.png
  src/assets/user/badges/badge_11.png
  src/assets/user/badges/badge_12.png
  src/assets/user/badges/badge_2.png
  src/assets/user/badges/badge_3.png
  src/assets/user/badges/badge_4.png
  src/assets/user/badges/badge_5.png
  src/assets/user/badges/badge_6.png
  src/assets/user/badges/badge_7.png
  src/assets/user/badges/badge_8.png
  src/assets/user/badges/badge_9.png
  src/assets/user/report.png
  src/components/common/Header.js
  src/components/common/History.js
  src/components/common/Top3Badges.js
  src/components/create/Form.js
  src/components/main/Carousel.js
  src/components/main/Recommendations.js
  src/components/user/Alarm.js
  src/components/user/Badge.js
  src/pages/Main/MainPage.js
  src/pages/User/AlarmPage.js
  src/pages/User/ReviewPage.js
  src/pages/User/UserProfilePage.js
Labels: 💄 publishing

#4 # 20231107 wowalswjd (김민정) 플로깅 상세 페이지, 마이페이지 관심/댓글 페이지 퍼블리싱
  src/App.js
  src/assets/PloggingDetail/ic_arrow.png
  src/assets/PloggingDetail/ic_share.png
  src/assets/common/ic_userbig.png
  src/assets/common/report.png
  src/components/PloggingDetail/CoCommentBox.js
  src/components/PloggingDetail/JoinFooter.js
  src/components/PloggingDetail/PloggingComment.js
  src/components/PloggingDetail/PloggingInfo.js
  src/components/PloggingList/FilteringBox.js
  src/components/PloggingList/PloggingListSection.js
  src/components/common/AdBanner.js
  src/components/common/CommentBox.js
  src/components/common/FloatingButton.js
  src/components/common/GradientLine.js
  src/components/common/Header.js
  src/components/common/PloggingPostBox.js
  src/components/common/useBottomDetection.js
  src/pages/MyPage/MyCommentPage.js
  src/pages/MyPage/MyInterestPage.js
  src/pages/Plogging/PloggingDetailPage.js
  src/pages/Plogging/PloggingListPage.js
  src/pages/PloggingListPage.js
  src/pages/User/ReviewPage.js
  src/pages/User/UserProfilePage.js
Labels: 💄 publishing

#5 20231107 songing01 (송지민) 카카오 소셜로그인 엑세스 토큰 발급 기능 구현
  .gitignore
  src/api/client.js
  src/components/common/Header.js
  src/pages/Login/KakaoLoginPage.js
  src/pages/Login/LoginPage.js
  src/pages/Main/MainPage.js
  src/pages/Plogging/CreatePlogPage.js
  src/pages/User/AlarmPage.js
  src/pages/User/ReviewPage.js
  src/pages/User/UserProfilePage.js
  src/pages/User/UserReportPage.js
Labels: ✨ feature

#6 # 20231109 wowalswjd (김민정) 마이페이지 4개/공식 행사 상세/쓰레기통 지도 페이지 퍼블리싱, 바텀시트 라이브러리 추가
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/common/ic_arrowup.png
  src/assets/common/ic_arrowup_white.png
  src/assets/common/ic_settings.png
  src/assets/mypage/ic_schedule.png
  src/assets/mypage/ic_star_white.png
  src/assets/mypage/ic_written.png
  src/components/PloggingDetail/JoinFooter.js
  src/components/PloggingDetail/PloggingComment.js
  src/components/common/CommentInput.js
  src/components/common/Footer.js
  src/components/common/UpdateProfile.js
  src/components/mypage/MyMenu.js
  src/components/trashmap/KakaoMap.js
  src/pages/Event/EventPage.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MySchedulePage.js
  src/pages/Plogging/PloggingDetailPage.js
  src/pages/TrashMap/TrashMapPage.js
Labels: 💄 publishing

#8 # 20231115 wowalswjd (김민정) 플로깅 상세 페이지 변경된 디자인 반영 및 기능 추가, Header 수정
  src/assets/common/ic_close.png
  src/assets/common/ic_comment.png
  src/assets/common/ic_delete.png
  src/assets/common/ic_report.png
  src/components/PloggingDetail/CoCommentBox.js
  src/components/PloggingDetail/JoinFooter.js
  src/components/PloggingDetail/ParticipateAlert.js
  src/components/PloggingDetail/PloggingComment.js
  src/components/PloggingDetail/UserBottomSheet.js
  src/components/PloggingDetail/UserInfoBox.js
  src/components/common/CommentBox.js
  src/components/common/CommentInput.js
  src/components/common/Header.js
  src/pages/Plogging/PloggingDetailPage.js
  src/styles/global.css
Labels: 💄 publishing

#9 #20231116 songing01 ( 송지민) 회원가입/로그인 API 연결, 모집글 작성 API 연결
  package-lock.json
  package.json
  src/api/client.js
  src/api/member.js
  src/api/posts.js
  src/components/common/Header.js
  src/components/common/NameSetting.js
  src/components/common/ValidNameCheck.js
  src/components/common/ageRange.js
  src/components/common/gender.js
  src/components/create/Form.js
  src/components/create/RangeSlider.js
  src/components/create/marks.js
  src/pages/Login/KakaoLoginPage.js
  src/pages/Login/LoginSettingsPage.js
  src/pages/Main/MainPage.js
Labels: 🐛 bugfix, ✨ feature

#10 #20231116 songing01 (송지민) 유저 프로필 조회 페이지 api 연결 및 탑3 배지 디자인 수정
  src/App.js
  src/api/member.js
  src/api/notification.js
  src/api/review.js
  src/assets/common/report.png
  src/components/common/Top3Badges.js
  src/components/user/Badge.js
  src/components/user/Notification.js
  src/pages/Login/LoginSettingsPage.js
  src/pages/User/NotificationPage.js
  src/pages/User/ReviewPage.js
  src/pages/User/UserProfilePage.js
Labels: 💄 publishing, ✨ feature

#11 #20231118 songing01 공식행사 캐러셀 api, 메인 플로깅 횟수 조회 api, 이미지 s3 업로드 요청 함수 구현, 모집글 작성 이미지 첨부, 사용자 신고/제보 하기 api 연결
  src/api/event.js
  src/api/posts.js
  src/api/report.js
  src/api/review.js
  src/api/s3presignedurl.js
  src/components/common/AddPhoto.js
  src/components/create/Form.js
  src/components/create/RangeSlider.js
  src/components/main/Carousel.js
  src/pages/Main/MainPage.js
  src/pages/User/UserProfilePage.js
  src/pages/User/UserReportPage.js
Labels: ✨ feature

#13 # 20231118 wowalswjd (김민정) 플로깅 리스트 페이지 관련 api 연결
  src/api/heart.js
  src/api/posts.js
  src/components/PloggingList/FilteringBox.js
  src/components/PloggingList/PloggingListSection.js
  src/components/common/FloatingButton.js
  src/components/common/PloggingPostBox.js
  src/components/common/ageRange.js
  src/components/common/gender.js
  src/pages/Plogging/PloggingListPage.js
Labels: ✨ feature

#14 # 20231120 wowalswjd (김민정) 마이페이지(관심 있는 글, 댓글 단 글) 연결, 플로깅 상세 페이지 api 연결 1차
  src/App.js
  src/api/comment.js
  src/api/heart.js
  src/api/posts.js
  src/components/PloggingDetail/PloggingInfo.js
  src/components/PloggingDetail/PostImageBox.js
  src/components/PloggingList/PloggingListSection.js
  src/components/common/Footer.js
  src/components/common/PloggingPostBox.js
  src/components/common/UpdateProfile.js
  src/components/common/ageRange.js
  src/components/common/checkPostsStatus.js
  src/components/common/gender.js
  src/components/common/time.js
  src/pages/MyPage/MyCommentPage.js
  src/pages/MyPage/MyInterestPage.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageUpdate.js
  src/pages/Plogging/PloggingDetailPage.js
Labels: 👀 enhancement, 💄 publishing, ✨ feature

#15 # 20231121 songing01 (송지민) 알림 조회 및 읽기 api 연결, 이미지 첨부 취소 기능, 토큰 재발급 api 연결, 프로필수정 이미지 관련 오류 해결
  package-lock.json
  package.json
  src/App.js
  src/api/client.js
  src/api/comment.js
  src/api/event.js
  src/api/heart.js
  src/api/member.js
  src/api/notification.js
  src/api/posts.js
  src/api/report.js
  src/api/review.js
  src/api/s3presignedurl.js
  src/assets/common/cancel.png
  src/assets/user/alarm/alarm_0.png
  src/assets/user/alarm/alarm_2.png
  src/assets/user/alarm/alarm_comment.png
  src/assets/user/alarm/alarm_plogging.png
  src/components/common/AddPhoto.js
  src/components/common/ageRange.js
  src/components/main/Carousel.js
  src/components/user/Notification.js
  src/index.js
  src/pages/Login/KakaoLoginPage.js
  src/pages/Login/LoginSettingsPage.js
  src/pages/Main/MainPage.js
  src/pages/MyPage/MyPageUpdate.js
  src/pages/User/NotificationPage.js
Labels: 🐛 bugfix, ✨ feature

#16 # 20231122 songing01 (송지민) 알림 api 관련 오류 해결, 퍼블리싱 오류 수정, 모집글 작성 날짜선택 예외처리
  src/components/common/AddPhoto.js
  src/components/common/Header.js
  src/components/create/Form.js
  src/pages/Main/MainPage.js
  src/pages/User/NotificationPage.js
Labels: 🐛 bugfix, 💄 publishing, ✨ feature

#17 # 20231122 wowalswjd (김민정) 플로깅 상세 페이지 api 연결 2차
  src/api/comment.js
  src/api/postjoin.js
  src/components/PloggingDetail/CoCommentBox.js
  src/components/PloggingDetail/JoinFooter.js
  src/components/PloggingDetail/ParticipateAlert.js
  src/components/PloggingDetail/PloggingComment.js
  src/components/PloggingDetail/UserBottomSheet.js
  src/components/PloggingDetail/UserInfoBox.js
  src/components/common/CommentBox.js
  src/components/common/CommentInput.js
  src/components/common/time.js
  src/pages/Plogging/PloggingDetailPage.js
Labels: 💄 publishing, ✨ feature

#18 # 20231122 songing01 (송지민) 알림조회 api url 수정, 광고배너 수정
  src/api/notification.js
  src/assets/ad/ad_1.png
  src/assets/ad/ad_2.png
  src/assets/ad/ad_3.png
  src/assets/common/loading.gif
  src/components/PloggingDetail/PloggingComment.js
  src/components/common/AdBanner.js
  src/pages/Login/KakaoLoginPage.js
  src/pages/User/NotificationPage.js
Labels: 👀 enhancement

#19 # 20231123 wowalswjd (김민정) 플로깅 상세 페이지 api 연결 3차
  src/api/comment.js
  src/api/posts.js
  src/assets/common/defaultImage/img_default1.png
  src/assets/common/defaultImage/img_default2.png
  src/assets/common/defaultImage/img_default3.png
  src/components/PloggingDetail/CoCommentBox.js
  src/components/PloggingDetail/PloggingComment.js
  src/components/common/CommentBox.js
  src/components/common/CommentInput.js
  src/components/common/PloggingPostBox.js
  src/pages/Plogging/PloggingDetailPage.js
Labels: 🐛 bugfix, ✨ feature

#20 # 20231123 songing01 (송지민) 공식행사 상세 페이지 api 연결 (댓글제외)
  public/favicon.ico
  public/favicon.png
  public/index.html
  src/App.js
  src/api/event.js
  src/components/create/Form.js
  src/components/main/Recommendations.js
  src/pages/Event/EventPage.js
Labels: ✨ feature

#21 #231123 송지민 (songing01) 광고배너 웹 버전 이미지 너비 수정
  src/components/common/AdBanner.js
  src/pages/Main/MainPage.js
Labels: 💄 publishing

#22 #231123 songing0 (송지민) 사용성 개선 요구사항 반영
  src/components/common/Footer.js
  src/components/common/Header.js
  src/pages/Main/MainPage.js
Labels: 💄 publishing, ✨ feature

#23 #231123 songing01 (송지민) 첫 로그인시 데이터 겟 에러 안나도록 새로고침 순서 변경
  src/pages/Login/KakaoLoginPage.js
  src/pages/Login/LoginSettingsPage.js
Labels: 🐛 bugfix

#25 # 20231123 wowalswjd (김민정) 마이페이지 내 플로깅 일정, 공식 행사 댓글 api 연결
  src/api/event.js
  src/api/posts.js
  src/components/PloggingDetail/ParticipateAlert.js
  src/components/common/CommentBox.js
  src/components/common/CommentInput.js
  src/pages/Event/EventPage.js
  src/pages/MyPage/MyPageUpdate.js
  src/pages/MyPage/MySchedulePage.js
Labels: 🐛 bugfix, 💄 publishing, ✨ feature

#26 # 20231124 wowalswjd (김민정) 마이페이지 수정 프로필 기존 이미지 오류 해결, 쓰레기통 지도 조회 api 연결
  package-lock.json
  package.json
  src/api/trashmap.js
  src/assets/trashmap/pin_recycle.png
  src/assets/trashmap/pin_trash.png
  src/components/common/AdBanner.js
  src/components/trashmap/KakaoMap.js
  src/pages/MyPage/MyPageUpdate.js
  src/pages/TrashMap/TrashMapPage.js
Labels: 🐛 bugfix, 💄 publishing, ✨ feature

#27 # 20231124 wowalswjd (김민정) 마이페이지 푸터 스크롤 문제 수정
  src/components/mypage/MyMenu.js
  src/pages/MyPage/MyPage.js
Labels: 🐛 bugfix, 💄 publishing

#28 # 20231124 wowalswjd (김민정) 현재 위치 마커 이미지, 각 쓰레기통 아이콘 별 바텀시트 추가
  src/assets/trashmap/ic_mapmarker.png
  src/components/trashmap/KakaoMap.js
  src/components/trashmap/TrashBottomSheet.js
  src/components/trashmap/feedbackList.js
  src/pages/TrashMap/TrashMapPage.js
Labels: 💄 publishing, ✨ feature

#29 # 20231124 wowalswjd (김민정) 모집글에 대댓글 삭제, 프로필 이미지 클릭 시 프로필 페이지 이동
  src/api/comment.js
  src/components/PloggingDetail/CoCommentBox.js
  src/components/PloggingDetail/PloggingComment.js
  src/components/PloggingDetail/UserBottomSheet.js
  src/components/PloggingDetail/UserInfoBox.js
  src/components/common/CommentBox.js
Labels: ✨ feature

#30 # 20231125 wowalswjd (김민정) 카카오 공유하기 기능 추가 및 기타 피드백 반영
  public/index.html
  public/navera1e408d06de8312045d72fdcb37db90e.html
  public/robots.txt
  src/components/PloggingDetail/KakaoShareBtn.js
  src/components/PloggingDetail/PloggingInfo.js
  src/pages/MyPage/MyPageUpdate.js
  src/pages/Plogging/PloggingDetailPage.js
Labels: 🐛 bugfix, 📝 documentation, ✨ feature

#31 # 20231127 wowalswjd (김민정) 플로깅 상세 하단 푸터 고정, 페이지에 로딩 중 추가, 쓰레기통 지도 바텀시트 커스텀
  src/components/PloggingDetail/JoinFooter.js
  src/components/PloggingDetail/PloggingComment.js
  src/components/trashmap/KakaoMap.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageUpdate.js
  src/pages/Plogging/PloggingDetailPage.js
  src/pages/TrashMap/TrashMapPage.js
Labels: 🐛 bugfix, 💄 publishing, ✨ feature

#33 # 20231129 wowalswjd (김민정) 플로깅 상세 페이지 오류 수정, og tag 추가
  public/Lets-JUPJUP.png
  public/index.html
  src/pages/Plogging/PloggingDetailPage.js
Labels: 🐛 bugfix, 📝 documentation
