Repository Lets-JUPJUP/JUPJUP-Front, pull requests merged in 2024-02, with the labels that each got.

#39 # 20240207 wowalswjd (김민정) 쓰레기통별 피드백 이력 조회 api 연결 및 관리자 페이지 퍼블리싱
  src/App.js
  src/api/trashmap.js
  src/assets/admin/ic_back.png
  src/assets/admin/logo_white.png
  src/components/admin/AdminHeader.js
  src/components/admin/AdminSideBar.js
  src/components/trashmap/KakaoMap.js
  src/components/trashmap/TrashBottomSheet.js
  src/pages/Admin/EventManagePage.js
  src/pages/TrashMap/TrashMapPage.js
  src/styles/global.css
Labels: 💄 publishing, ✨ feature

#42 # 20240212 wowalswjd (김민정) 공식행사, 쓰레기통 관리자 페이지 api 연결
  package-lock.json
  package.json
  src/api/admin.js
  src/components/admin/event/EventManage.js
  src/components/admin/event/EventRegister.js
  src/components/admin/event/EventRow.js
  src/components/admin/trash/TrashDetail.js
  src/components/admin/trash/TrashManage.js
  src/components/admin/trash/TrashRow.js
Labels: ✨ feature

#43 # 20240218 songing01 (송지민) 관리자페이지 접근제한 설정, 강제 탈퇴 유저 구분
  src/App.js
  src/api/member.js
  src/components/admin/AdminHeader.js
  src/components/admin/user/DeleteModal.js
  src/components/admin/user/UserManage.js
  src/components/common/Footer.js
  src/router/PrivateRoute.js
Labels: 👀 enhancement, ✨ feature

#45 # 20240228 wowalswjd (김민정) 헤더 뒤로 가기 버튼 추가 및 플로깅 리스트 페이지 리팩토링
  src/assets/common/ic_back_main.png
  src/components/PloggingList/FilteringBox.js
  src/components/common/Header.js
  src/pages/Plogging/PloggingListPage.js
Labels: 👀 enhancement, ✨ feature
